name: Release-Container
on:
  push:
    branches: 
    - master
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set tag
      id: tags
      run: echo ::set-output name=tag::${GITHUB_SHA}
    - name: Build and push Docker image
      uses: docker/build-push-action@v1
      with:  
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_FOR_GHCR }}
        registry: ghcr.io/maximalyono/yuhu

#        tags: yuhu
        tag_with_ref: true
        tag_with_ref: true
