name: Release-Container
on:
  push:
    branches: 
    - master
jobs:
  deploy-app:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set tag
      id: tags
      run: echo ::set-output name=tag::${GITHUB_SHA}
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN_FOR_GHCR }}
        registry: docker.pkg.github.com
        repository: test-ghcr/package-ghcr
        tag_with_ref: true
      
      #run: docker image build -t test-ghcr:${{ steps.tags.outputs.tag }} .
      
 #   - name: Release
 #     env:
 #       HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
 #     run: heroku container:release -a palembang-digital web
